name: time_trace

server:
  listen: localhost
  port: "7070"

log:
  write_to_file: true
  path: ttrace.log

users:
- name: root
  password: super_secret_password
  cmds:
  - '*'

# Also you can use this for multiple users and limited commands
# users:
#   - name: root
#     password: super_secret_password
#     cmd:
#       - '*' # all commands.
#   - name: developer
#     password: secret_password
#     cmd:
#       - 'GET'
#       - 'PUSH'
#       - 'DEL'