name: time_trace

server:
  listen: localhost
  port: "7070"

log:
  path: ttrace.log

users:
- name: root
  pass_word: super_secret_password
  cmds:
  - '*'
# Also you can use this for multiple users and limited commands
# users:
#   - name: root
#     pass_word: super_secret_password
#     cmd:
#       - * # all commands.
#   - name: developer
#     password: secret_password
#     cmd:
#       - GET
#       - PUSH
#       - DEL